language: android
dist: trusty
android:
    components:
        - build-tools-28.0.3
        - android-28
        - add-on
        - extra

    licenses:
        - 'android-sdk-license-.+'
        - 'google-sdk-license-.+'

    script: ./gradlew build
