language: android
dist: trusty
android:
    components:
        - build-tools-26.0.2
        - android-26
        - add-on
        - extra

    licenses:
        - 'android-sdk-license-.+'
        - 'google-sdk-license-.+'

    script: ./gradlew build
